<?
$PERM["admin"]["8"]="R";
$PERM["admin"]["11"]="R";
$PERM["admin"]["10"]="R";
$PERM["admin"]["6"]="R";
$PERM["admin"]["18"]="R";
$PERM["admin"]["7"]="R";
$PERM["admin"]["*"]="D";
$PERM["tools"]["9"]="T_8";
$PERM["rk.php"]["9"]="T_8";
?>