<?php
if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
if($USER->IsAuthorized() || $arParams["ALLOW_AUTO_REGISTER"] == "Y") {
    if($arResult["USER_VALS"]["CONFIRM_ORDER"] == "Y" || $arResult["NEED_REDIRECT"] == "Y") {
        if(strlen($arResult["REDIRECT_URL"]) > 0) {
            $APPLICATION->RestartBuffer();
            ?>
            <script type="text/javascript">
                window.top.location.href='<?=CUtil::JSEscape($arResult["REDIRECT_URL"])?>';
            </script>
            <?
            die();
        }
    }
}

?>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
      crossorigin=""/>


<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
        integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
        crossorigin=""></script>

<!-- Load Esri Leaflet from CDN -->
<script src="https://unpkg.com/esri-leaflet@2.5.0/dist/esri-leaflet.js"
        integrity="sha512-ucw7Grpc+iEQZa711gcjgMBnmd9qju1CICsRaryvX7HJklK0pGl/prxKvtHwpgm5ZHdvAil7YPxI1oWPOWK3UQ=="
        crossorigin=""></script>

<!-- Load Esri Leaflet Geocoder from CDN -->
<link rel="stylesheet" href="https://unpkg.com/esri-leaflet-geocoder@2.3.3/dist/esri-leaflet-geocoder.css"
      integrity="sha512-IM3Hs+feyi40yZhDH6kV8vQMg4Fh20s9OzInIIAc4nx7aMYMfo+IenRUekoYsHZqGkREUgx0VvlEsgm7nCDW9g=="
      crossorigin="">
<script src="https://unpkg.com/esri-leaflet-geocoder@2.3.3/dist/esri-leaflet-geocoder.js"
        integrity="sha512-HrFUyCEtIpxZloTgEKKMq4RFYhxjJkCiF5sDxuAokklOeZ68U2NPfh4MFtyIVWlsKtVbK5GD2/JzFyAfvT5ejA=="
        crossorigin=""></script>


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-88170340-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-88170340-1');
</script>

<style type="text/css">
    @keyframes ldio-oojr64tg0sa {
        0% { transform: rotate(0) }
        100% { transform: rotate(360deg) }
    }
    .ldio-oojr64tg0sa div { box-sizing: border-box!important }
    .ldio-oojr64tg0sa > div {
        position: absolute;
        width: 69px;
        height: 69px;
        top: 15.5px;
        left: 15.5px;
        border-radius: 50%;
        border: 5px solid #000;
        border-color: #7fa5f0 transparent #7fa5f0 transparent;
        animation: ldio-oojr64tg0sa 0.4385964912280702s linear infinite;
    }
    .ldio-oojr64tg0sa > div:nth-child(2) { border-color: transparent }
    .ldio-oojr64tg0sa > div:nth-child(2) div {
        position: absolute;
        width: 100%;
        height: 100%;
        transform: rotate(45deg);
    }
    .ldio-oojr64tg0sa > div:nth-child(2) div:before, .ldio-oojr64tg0sa > div:nth-child(2) div:after {
        content: "";
        display: block;
        position: absolute;
        width: 5px;
        height: 5px;
        top: -5px;
        left: 27px;
        background: #7fa5f0;
        border-radius: 50%;
        box-shadow: 0 64px 0 0 #7fa5f0;
    }
    .ldio-oojr64tg0sa > div:nth-child(2) div:after {
        left: -5px;
        top: 27px;
        box-shadow: 64px 0 0 0 #7fa5f0;
    }
    .loadingio-spinner-dual-ring-qmu8mqsk81 {
        width: 38px;
        height: 38px;
        display: inline-block;
        overflow: hidden;
        background: none;
    }
    .ldio-oojr64tg0sa {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(0.38);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }
    .ldio-oojr64tg0sa div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>

<?php

$APPLICATION->SetAdditionalCSS($templateFolder."/style_cart.css");
$APPLICATION->SetAdditionalCSS($templateFolder."/style.css");

//pre($arResult["GRID"]["ROWS"]);
//die();
?>
<div class="autorized-user-unreg">
<?
//Authorization if use dont't registrate
global $USER;
if ($USER->IsAuthorized()){
    $user_id = CUser::GetID();
    $rsUser = CUser::GetByID($user_id);
    $arUser = $rsUser->Fetch();

    // print_r("Добро пожаловать на наш сайт!<br>");
    // print_r("ID пользователя: ".$USER->GetID()."<br>");
    // print_r("Логин пользователя: ".$USER->GetLogin()."<br>");
    // print_r("Имя и фамилия пользователя: ".$USER->GetFullName()."<br>");
    } else {?>

    <a href="#" class="link-regular-customer" > я постоянный клиент</a>
<!--    class="help-regular-customer"-->
    <span  class="help-regular-customer alert alert-info" >пожалуйста, авторизуйтесь.</span>

    <div id="show-regular-customer" class="regular-customer">
    <span class="question-txt question-txt-autorized">Если вы уже зарегистрированы - введите логин и пароль!</span>
    <?$APPLICATION->IncludeComponent(
    "bitrix:system.auth.form",
    ".default",
        Array(
            "REGISTER_URL" => "/registr/index.php",
            "FORGOT_PASSWORD_URL" => "/personal/profile/?forgot_password=yes",
            "PROFILE_URL" => "/personal/profile/",
            "SHOW_ERRORS" => "Y"
        )
    );
}?>
    </div>
</div>
<a name="order_form"></a>

<div id="order_form_div" class="order-checkout <?php echo $USER->IsAuthorized() ? 'bx-content col-md-9 col-sm-8' : ''?>">
<NOSCRIPT>
    <div class="errortext"><?=GetMessage("SOA_NO_JS")?></div>
</NOSCRIPT>
<script type="text/javascript">
<?php
$i=0;
$b=0;
$CPrice = new CPrice;
echo 'var $el=new Array();';
echo 'var $end=new Array();';
$stabpr = '';
foreach($arResult["GRID"]["ROWS"] as $key=>$row){
    $id = $row['data']['PRODUCT_ID'];
    $PRICE_TYPE_ID = 2;
    $res = $CPrice->GetList(
        array(),
        array(
            "PRODUCT_ID" => $id,
            "CATALOG_GROUP_ID" => $PRICE_TYPE_ID
        ));
    $arr = $res->Fetch();
    $arResult['GRID']['ROWS'][$key]['data']['DISCOUNT_PRICE'] = $arr['PRICE']-$row['data']['PRICE'];
    //pre($arr['PRICE']);
    $db_props = CIBlockElement::GetProperty(intval(2),intval($id),array("sort" => "asc"),array("CODE"=>"CONSTANT_PRICE"));
    $CONSTANT_PRICE = $db_props->Fetch();
    if((true===empty($arr['PRICE']) || $arr['PRICE']==0)
        && true===empty($CONSTANT_PRICE['VALUE'])){
        //товары на которые распространяется скидка по
        //дисконтной карте
        //echo ' $el['.$i.']=['.$row['data']['PRICE'].','.$row['data']['PRODUCT_ID'].','.$row['data']['QUANTITY'].'];';
        //$i++;
        //echo $i.'<br/>';
    } else {
        //акционные товары на которые не распространяется скидка по
        //дисконтной карте
        $a = round((($arr['PRICE']-$row['data']['PRICE'])*100)/$arr['PRICE']);
        $arResult['GRID']['ROWS'][$key]['data']['DISCOUNT_PRICE_PERCENT_FORMATED'] = $a.'%';
        $sum = $row['data']['PRICE'] * $row['data']['QUANTITY'];
        echo '$end['.$b.']=['.$sum.'];';
        $b++;
    }
}
echo 'var $index='.$i.';';
unset($CPrice);?>
let $script = "<?=$templateFolder."/orderWatch.php";?>";
let $res;
//var $II = <?=$USER->GetID();?>;
<?include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/dkscript.js");?>
</script>
<?
if (!function_exists("getColumnName")) {
    function getColumnName($arHeader) {
        return (strlen($arHeader["name"]) > 0) ? $arHeader["name"] : GetMessage("SALE_".$arHeader["id"]);
    }
}

if (!function_exists("cmpBySort")) {
    function cmpBySort($array1, $array2) {
        if (!isset($array1["SORT"]) || !isset($array2["SORT"]))
            return -1;

        if ($array1["SORT"] > $array2["SORT"])
            return 1;

        if ($array1["SORT"] < $array2["SORT"])
            return -1;

        if ($array1["SORT"] == $array2["SORT"])
            return 0;
    }
}
?>

<div class="bx_order_make">
    <?
    if(!$USER->IsAuthorized() && $arParams["ALLOW_AUTO_REGISTER"] == "N") {
        if(!empty($arResult["ERROR"]))
        {
            foreach($arResult["ERROR"] as $v)
                echo ShowError($v);
        }
        elseif(!empty($arResult["OK_MESSAGE"]))
        {
            foreach($arResult["OK_MESSAGE"] as $v)
                echo ShowNote($v);
        }

        include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/auth.php");
    }
    else {
        if($arResult["USER_VALS"]["CONFIRM_ORDER"] == "Y" || $arResult["NEED_REDIRECT"] == "Y") {
            if(strlen($arResult["REDIRECT_URL"]) == 0)
            {
                include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/confirm.php");
            }
        }
        else {
            ?>
            <script type="text/javascript">
            <?if(CSaleLocation::isLocationProEnabled()):?>

                <?
                // spike: for children of cities we place this prompt
                $city = \Bitrix\Sale\Location\TypeTable::getList(array('filter' => array('=CODE' => 'CITY'), 'select' => array('ID')))->fetch();
                ?>
                BX.saleOrderAjax.init(<?=CUtil::PhpToJSObject(array(
                    'source' => $this->__component->getPath().'/get.php',
                    'cityTypeId' => intval($city['ID']),
                    'messages' => array(
                        'otherLocation' => '--- '.GetMessage('SOA_OTHER_LOCATION'),
                        'moreInfoLocation' => '--- '.GetMessage('SOA_NOT_SELECTED_ALT'), // spike: for children of cities we place this prompt
                        'notFoundPrompt' => '<div class="-bx-popup-special-prompt">'.GetMessage('SOA_LOCATION_NOT_FOUND').'.<br />'.GetMessage('SOA_LOCATION_NOT_FOUND_PROMPT', array(
                            '#ANCHOR#' => '<a href="javascript:void(0)" class="-bx-popup-set-mode-add-loc">',
                            '#ANCHOR_END#' => '</a>'
                        )).'</div>'
                    )
                ))?>);
            <?endif?>

            let BXFormPosting = false;

            function userFIO() {
                let fio = ($("#np_last_name").val().length !== 0 && $("#np_first_name").val().length !== 0 && $("#np_second_name").val().length !== 0) ? ($("#np_last_name").val() + " " + $("#np_first_name").val() + " " + $("#np_second_name").val()) : '';
                $("#courier-delivery-fio").val(fio);
            }

            function getCoords(elem) {
                let box = elem.getBoundingClientRect();

                return box.top + pageYOffset;
            }

            function requiredFieldsValidate(requiredFieldsCourier) {

                let requiredFields = [
                    "#np_last_name",
                    "#np_first_name",
                    "#np_second_name",
                    "#ORDER_PROP_2",
                    "#ORDER_PROP_3"
                ].concat(requiredFieldsCourier);

                let errArray = [];

                requiredFields.map(el => {
                    let item = document.querySelector(el);
                    let errFlag = false;

                    if (item.classList.contains("geocoder-control-input")) {
                        let index = item.value.indexOf(',');
                        if (item.value.slice(index).length <= 2) {
                            errFlag = true;
                        }
                    }

                    if (item.value.length == 0 || errFlag) {
                        item.classList.add('red-border');
                        errArray.push(getCoords(item));

                        showErrorBalloon($("#ORDER_CONFIRM_BUTTON"), "Есть незаполненные поля", 15);
                        return false;
                    } else {
                        item.classList.remove('red-border');
                        $("p.balloon-alert2").remove();
                    }
                });

                const min = Math.min(...errArray);
                let firstRowHeight = 0;
                if (window.matchMedia("(max-width: 768px)").matches) {
                    firstRowHeight = $("#first_row").height();
                }
                $('html').animate({
                        scrollTop: min - firstRowHeight - 20
                    }, 700
                );
            }

            function submitForm(val) {

                // if ($("#ORDER_PROP_7").val() == "ord_oblast_apt" || $("#ORDER_PROP_7").val() == "")
                //     return false;

                userFIO();

                $("#ORDER_PROP_17, #ORDER_PROP_18, #ORDER_PROP_19").val("");
                $("#ORDER_PROP_17").val($(".np_street_wrap input[name=np_street]").val());
                $("#ORDER_PROP_18").val($(".np_street_wrap input[name=np_house]").val());
                $("#ORDER_PROP_19").val($(".np_street_wrap input[name=np_flat]").val());
                $("#ORDER_PROP_1").val($("#np_last_name").val() + " " + $("#np_first_name").val() + " " + $("#np_second_name").val());
                $("#ORDER_PROP_34").val($("#courier-delivery-fio").val());
                $("#ORDER_PROP_35").val($("#courier-delivery-phone").val());
                $("#ORDER_PROP_36").val($('#delivery-courier-address').val());
                $("#ORDER_PROP_37").val($('#delivery-cost').val());
                $("#ORDER_PROP_38").val($('#delivery-courier-lat').val());
                $("#ORDER_PROP_39").val($('#delivery-courier-lng').val());

                let curentVariant = $(".delivery-variants>ul li.checked").attr('id');

                if (curentVariant == "li_17") {
                    requiredFieldsValidate([
                        "#ORDER_PROP_14",
                        "#ORDER_PROP_16",
                        "#ORDER_PROP_17",
                        "#ORDER_PROP_18"
                    ]);
                } else if (curentVariant == "li_18") {
                    requiredFieldsValidate([
                        "#ORDER_PROP_14",
                        "#ORDER_PROP_16",
                        "#ORDER_PROP_20"
                    ]);
                } else if (curentVariant == "li_19") {
                    requiredFieldsValidate([
                        "#ORDER_PROP_21",
                        "#ORDER_PROP_22",
                        "#ORDER_PROP_23"
                    ]);
                } else if (curentVariant == "li_20") {
                    requiredFieldsValidate([
                        "#courier-delivery-fio",
                        "#courier-delivery-phone",
                        // "#delivery-courier-address",
                        ".geocoder-control-input.leaflet-bar"
                    ]);
                } else if (curentVariant == "li_12") {
                    requiredFieldsValidate([]);
                }

                // if (BXFormPosting === true)
                //     return true;

                BXFormPosting = true;
                if(val != 'Y')
                    BX('confirmorder').value = 'N';

                let errorValidate = document.querySelector(".red-border");

                if (!errorValidate) {
                    let orderForm = BX('ORDER_FORM');
                    BX.showWait();

                    <?if(CSaleLocation::isLocationProEnabled()):?>
                    BX.saleOrderAjax.cleanUp();
                    <?endif?>

                    BX.ajax.submit(orderForm, ajaxResult);

                    return true;
                }
            }

            $("#ORDER_PROP_4 option[VALUE=NAL_COURIER], #ORDER_PROP_4 option[VALUE=CARD_COURIER]").remove();

            function ajaxResult(res) {
                let orderForm = BX('ORDER_FORM');
                try {
                    // if json came, it obviously a successfull order submit

                    let json = JSON.parse(res);
                    BX.closeWait();

                    if (json.error) {
                        BXFormPosting = false;
                        return;
                    }
                    else if (json.redirect) {
                        window.top.location.href = json.redirect;
                    }
                }
                catch (e) {
                    // json parse failed, so it is a simple chunk of html
                    $("#ORDER_FORM .errortext").remove()
                    BXFormPosting = false;
                    let html = res;
                    let dom = document.createElement('html');
                    dom.innerHTML = html;
                    let errors = Array.from(dom.querySelectorAll('.errortext')).map(el => el.innerText);
                    for (let i = 0; i < errors.length; i ++) {
                        $("#ORDER_FORM").prepend('<p><font class="errortext">' + errors[i] + '</font></p>')
                    }
//                    BX('order_form_content').innerHTML = res;

                    <?if(CSaleLocation::isLocationProEnabled()):?>
                        BX.saleOrderAjax.initDeferredControl();
                    <?endif?>
                }

                BX.closeWait();
                BX.onCustomEvent(orderForm, 'onAjaxSuccess');
            }

            function SetContact(profileId) {
                BX("profile_change").value = "Y";
                submitForm();
            }
            </script>
            <?if($_POST["is_ajax_post"] != "Y") {
                ?>
            <?php if ($USER->IsAuthorized()){?>
<!--                <div class="bx-content col-md-9 col-sm-8">-->
            <?php }?>
            <form action="<?=$APPLICATION->GetCurPage();?>" method="POST" name="ORDER_FORM" id="ORDER_FORM" enctype="multipart/form-data">
                <?=bitrix_sessid_post()?>
                <div id="order_form_content">
                <?
            } else {
                $APPLICATION->RestartBuffer();
            }

            if($_REQUEST['PERMANENT_MODE_STEPS'] == 1) {
                ?>
                <input type="hidden" name="PERMANENT_MODE_STEPS" value="1" />
                <?
            }

            if(!empty($arResult["ERROR"]) && $arResult["USER_VALS"]["FINAL_STEP"] == "Y") {
                foreach($arResult["ERROR"] as $v)
                    echo ShowError($v);
                ?>
                <script type="text/javascript">
                    top.BX.scrollToNode(top.BX('ORDER_FORM'));
                </script>
                <?
            }

            include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/person_type.php");

            include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/props.php");

            if ($arParams["DELIVERY_TO_PAYSYSTEM"] == "p2d") {
                include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/paysystem.php");
                include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/delivery.php");
            }

            include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/related_props.php");

            include($_SERVER["DOCUMENT_ROOT"].$templateFolder."/summary.php");
            if(strlen($arResult["PREPAY_ADIT_FIELDS"]) > 0)
                echo $arResult["PREPAY_ADIT_FIELDS"];
            ?>

            <?if($_POST["is_ajax_post"] != "Y") {
                ?>
                    </div>
                    <input type="hidden" name="confirmorder" id="confirmorder" value="Y">
                    <input type="hidden" name="profile_change" id="profile_change" value="N">
                    <input type="hidden" name="is_ajax_post" id="is_ajax_post" value="Y">
                    <input type="hidden" name="json" value="Y">
                    <div class="bx_ordercart_order_pay_center">
                        <button href="javascript:void();" onclick="submitForm('Y'); return false;" id="ORDER_CONFIRM_BUTTON" class="checkout mc-button" style="display:none;"><?=GetMessage("SOA_TEMPL_BUTTON")?></button>
                    </div>
                    <?if(!isset($_GET['ORDER_ID'])){
                        echo '<a href="/" class="mc-button makeorder">Продолжить покупки</a>';
                    }
                    ?>
                </form>
                    <?php if ($USER->IsAuthorized()){?>
<!--                        </div>-->
                    <?php }?>
                <script>
                    let confirmInput1 = document.getElementById('ORDER_PROP_1');
                    let confirmInput2 = document.getElementById('ORDER_PROP_2');
                    let confirmInput3 = document.getElementById('ORDER_PROP_3');
                    let order = document.getElementById('order-wrap');
                    let orderForm = document.getElementById('ORDER_FORM');
                    let oblApt = document.getElementById('ord_oblast_apt');

                    inp_loc = document.getElementById('ORDER_PROP_7');
                    inp_loc_adr = document.getElementById('ORDER_PROP_5');

                    ord_oblast_name_list = document.getElementById('ord_oblast_name_list');
                    ord_oblast_name = document.getElementById('ord_oblast_name');
                    ord_oblast = document.getElementById('ord_oblast');

                    ord_city_name_list = document.getElementById('ord_city_name_list');
                    ord_pharmacy_name_list = document.getElementById('ord_pharmacy_name_list');
                    ord_city = document.getElementById('ord_city');
                    ord_pharmacy = document.getElementById('ord_pharmacy');
                    ord_city_name = document.getElementById('ord_city_name');
                    ord_pharmacy_name = document.getElementById('ord_pharmacy_name');
                    ORDER_CONFIRM_BUTTON = document.getElementById('ORDER_CONFIRM_BUTTON');
                    ORDER_CONFIRM_BUTTON.style.display = 'none';
                    let question = document.getElementById('question');
                    let itogCity;

                    function openPharmChangeList() {
                        let cityChange = document.querySelector('#ord_oblast');
                        let pharmacyChange = document.querySelector('#ord_city');
                        if (cityChange.value.length !== 0) {
                            oblApt.style.display = 'block';
                            $("#ord_city").show();
                        } else {
                            pharmacyChange.style.display = 'none';
                        }
                    }

                    let magnifierIcon = document.querySelector('#ord_city .fa-search');
                    magnifierIcon.addEventListener('click', () => {
                        openPharmChangeList();
                    })

                    //Отменяем нажате Enter
                    orderForm.onkeypress = function(e) {
                        e = e || window.event;
                        if (e.keyCode == 13 || e.which == 13)
                        e.preventDefault ? e.preventDefault() : e.returnValue = false;
                    };

                    // Поля ввода данных(ФИО, мыло, телефон)
                    confirmInput1.onkeyup = function(e) {
                        if (confirmInput1.value != '' &&
                            confirmInput2.value != '' &&
                            ord_oblast.value != '' &&
                            $("#ord_city input").val() != '' &&
                            confirmInput3.value != '') {
                            ORDER_CONFIRM_BUTTON.style.display = 'block';
                        }

                       let eraseTo = e.keyCode;
                       question.style.display = 'none';
                       confirmInput1.classList.remove('order-empty-error');
                       confirmInput1.placeholder = '';

                       //при нажатии backspace пропадает кнопка и добавляются красные поля
                       if (eraseTo == 8 && $(this).val() === '') {
                           if (!$("#ord_oblast").val())
                                question.style.display = 'inline-block';
                       }
                    }
                    // Поля ввода данных(ФИО, мыло, телефон)
                    confirmInput2.onkeyup = function(e) {
                        if (confirmInput1.value != '' &&
                            confirmInput2.value != '' &&
                            ord_oblast.value != '' &&
                            $("#ord_city input").val() != '' &&
                            confirmInput3.value != '') {
                            ORDER_CONFIRM_BUTTON.style.display = 'block';
                        }
                       let eraseTo = e.keyCode;
                       question.style.display = 'none';
                       confirmInput2.classList.remove('order-empty-error');
                       confirmInput2.placeholder = '';

                       //при нажатии backspace пропадает кнопка и добавляются красные поля
                       if (eraseTo == 8 && $(this).val() === '') {
                           question.style.display = 'inline-block';
                       }
                    }
                    // Поля ввода данных(ФИО, мыло, телефон)
                    confirmInput3.onkeyup = function(e) {
                       let eraseTo = e.keyCode;
                       question.style.display = 'none';
                       confirmInput3.classList.remove('order-empty-error');
                       confirmInput3.placeholder = '';
                    }

                    ord_oblast_name.onclick=function(e){
                        let el = e.target;
                        if (el.classList.contains('row-list')) {
                            return false;
                        }

                        $.ajax({
                            type: "POST",
                            url: "/bitrix/templates/eshop_adapt_MC/components/medservice/MCsale.order.ajax/orderMC/delivery/check.php",
                            data: {
                                action: "getCourierVariants",
                                city: el.innerText
                            },
                            success: function(resp) {
                                if (resp == 1) {
                                    $(".delivery-list-wrap").removeClass('courier_hidden');
                                    let courierWrap = document.querySelector('#li_20');
                                    courierWrap.parentElement.classList.add('green-border')
                                } else {
                                    $("#li_12 input").click();
                                    $(".delivery-courier").remove();
                                    $("ul.delivery-list li#li_20").parent().addClass('courier_hidden');
                                }
                            }
                        });

                        id = el.id;
                        //console.log(el);
                        ord_oblast.value = '';
                        ord_oblast.value += el.innerHTML;
                        ord_oblast_name.style.display='none';
                        // ord_city.innerHTML = 'Начните вводить адрес аптеки...';
                        ord_oblast_apt.style.display = 'block';
                        itogCity = ord_oblast.value;

                        let addresses = new Array();

                        if (itogCity == '') {
                            oblApt.style.display = 'none';
                        } else {
                            // $(".location-address").show();
                        }

                        // Добавляем значение улиц в пустой список, при выборе города
                        let cityAll = document.querySelectorAll('#ord_oblast_name li.up-hood');
                        for (let i = 0; i < cityAll.length; i++) {
                            if (itogCity == cityAll[i].innerHTML) {
                                let op = cityAll[i].nextSibling.cloneNode(true);
                                addresses.push(op)
                            }
                        }

                        $(".location-address input[type=search]").on('keyup', function () {
                            oblApt.style.display = 'block';
                            let addresses2 = new Array();
                            $("#ord_oblast_apt").html('')
                            for (let item of addresses) {
                                if (item.firstChild.data.toLowerCase().indexOf($(this).val().toLowerCase()) != -1) {
                                    // var op = item.nextSibling.cloneNode(true);
                                    addresses2.push(item)
                                    // console.log(item)
                                }

                            }

                            let sortedElements = Array.from(addresses2).sort(function(a, b) {
                                let c = a.textContent;
                                let d = b.textContent;
                                return c < d ? -1 : c > d ? 1 : 0;
                            });

                            for (let element of sortedElements) {
                                oblApt.appendChild(element)
                            }
                        })

                        let sortedElements = Array.from(addresses).sort(function(a, b) {
                            let c = a.textContent;
                            let d = b.textContent;
                            return c < d ? -1 : c > d ? 1 : 0;
                        });

                        for (let element of sortedElements) {
                            oblApt.appendChild(element)
                        }

                        $('html').animate({
                            marginTop: (0 - ($(".order-empty-error").eq(0).offset().top - $(window).scrollTop())) + "px"
                        }, 1000)
                    };

                    // Показ балуна
                    function showErrorBalloon(el, mess, marginTop = 0) {
                        $('.balloon-alert2').remove();
                        el.before('<p class="balloon-alert2"><span class="arrow-alert"> </span>' + mess + '</p>')
                        $(".balloon-alert2").css({
                            left: el.position().left + "px"
                        }).animate({opacity: 1, top: "-" + (el.height() + 15 + marginTop) + "px"}, 100)
                    }

                    // Запрет ввода латиницы
                    function notLatin(el, mess) {
                        if (el.context.name == 'np_house' || el.context.name == 'np_flat') {
                            if (el.val().length == 1) {
                                el.val(el.val().replace(/0/, ''))
                            }
                            el.val(el.val().replace(/\D/, ''))
                        } else {
                            let reg = /[a-z]+/i;
                            if (el.val().search(reg) != -1) {
                                el.val(el.val().replace(reg, ''))
                                showErrorBalloon(el, mess, 0);
                            } else {
                                el.removeAttr('style').removeClass('fio-error')
                            }
                        }
                    }

                    let currentFioArray = $("#ID_PROFILE_ID").length == 0 ? ['', '', ''] : ($("#ID_PROFILE_ID").attr('type') == 'hidden' ? $("#ID_PROFILE_ID").prev().text().split(" ") : $("#ID_PROFILE_ID option:selected").text().split(" "))

                    $("#ORDER_PROP_1").attr('type', 'hidden').after("<div class='fio-wrapper'><input type='text' id='np_last_name' onkeyup='notLatin($(this), \"Разрешена только кириллица\")' placeholder='Фамилия' value='" + (currentFioArray[0] != '' ? currentFioArray[0] : '') + "'></div><div class='fio-wrapper'><input type='text' id='np_first_name' onkeyup='notLatin($(this), \"Разрешена только кириллица\")' placeholder='Имя' value='" + (currentFioArray[1] != '' ? currentFioArray[1] : '') + "'></div><div class='fio-wrapper'><input type='text' id='np_second_name' onkeyup='notLatin($(this), \"Разрешена только кириллица\")' placeholder='Отчество' value='" + (currentFioArray[2] != '' ? currentFioArray[2] : '') + "'></div>").wrap("<div class='fio-wrapper'></div>")

                    // Выбор вариантов доставки
                    function deliveryVariants() {
                        let url = "/bitrix/templates/eshop_adapt_MC/components/medservice/MCsale.order.ajax/orderMC/delivery/check.php";

                        let deliveryDisableGlobal = false

                        function deliveryDisable() {
                            $("#ORDER_PROP_4 option[VALUE=NAL_COURIER], #ORDER_PROP_4 option[VALUE=CARD_COURIER]").remove();
                            $(".delivery-courier, .advanced_courier").remove();
                            $.ajax({
                                type: "POST",
                                async: false,
                                url: url,
                                data: {
                                    action: "deliveryOption"
                                },
                                success: function(resp) {
                                    deliveryDisableGlobal = false
                                    if (resp.length > 0) {
                                        if ($("#popup-message").css('display') == 'none') {
                                            $("#popup-message").html(resp)
                                            $("#popup-message").css({color: 'white'})
                                        }

                                        let popup = BX.PopupWindowManager.create("popup-message", null, {
                                            content: resp,
                                            darkMode: true,
                                            autoHide: true
                                        });

                                        setTimeout(function () {
                                            popup.show();
                                            BX.PopupWindowManager.onPopupDestroy(popup)
                                        }, 100)

                                        deliveryDisableGlobal = true

					let windowTop = parseInt($(window).scrollTop())
                                        let popupHeight = parseInt($("#popup-message").height())
                                        let popupTop = parseInt(windowTop - popupHeight)
                                        $("body #popup-message").css({top: popupTop + "px", opacity: 0}).animate({
                                            top: windowTop + "px",
                                            opacity: 1
                                        })
                                    }
                                }
                            })
                        }

                        $("#relPrps h4").after('<div class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                            '<div></div><div><div></div></div></div></div>')

                        $.ajax({
                            type: "POST",
                            url: url,
                            data: {
                                action: 'deliveryCheck'
                            },
                            success: function(response) {
                                $(".ldio-oojr64tg0sa").remove();
                                let obj = JSON.parse(response);
                                let deliveryVar = '';
                                if (obj.length > 0) {
                                    for (let item = 0; item < obj.length; item++) {
                                        if (item == 0) {
                                            $("#ORDER_PROP_15").val(obj[item]);
                                        }

                                        let itemArr = obj[item].split(';')

                                        deliveryVar += (itemArr[2].length != 0 ? '<li class="delivery-img"><img src="' + itemArr[2] + '">' + '</li>' : '') + "<li " + (item == 0 ? ' class="checked"' : '') + " id='li_" + itemArr[0] + "'><input type='radio' name='variants_radio'/> <span>" + (item == 0 ? 'Забрать в аптеке' : itemArr[1]) + "</span></li>";
                                    }
                                    $("#relPrps h4").after("<div class='delivery-variants'><ul class='delivery-list'>" + deliveryVar + "</ul></div>");
                                    $(".delivery-list li:nth-child(1)").wrapAll("<div class='delivery-list-wrap'></div");
                                    $(".delivery-list li:nth-child(2), .delivery-list li:nth-child(3), .delivery-list li:nth-child(4)").wrapAll("<div class='delivery-list-wrap'></div>");
                                    $(".delivery-list > li:nth-of-type(1), .delivery-list > li:nth-of-type(2)").wrapAll("<div class='" + ($(".delivery-list > li:nth-of-type(1)").attr('id') == 'li_20' ? 'courier_hidden' : '') + " delivery-list-wrap'></div");
                                    $(".delivery-list > li:nth-of-type(1)").wrapAll("<div class='" + ($(".delivery-list > li:nth-of-type(1)").attr('id') == 'li_20' ? 'courier_hidden' : '') + " delivery-list-wrap'></div");
                                    // $(".delivery-list > li").wrapAll("<div class='delivery-list-wrap'></div>");
                                    $(".delivery-list").prepend($(".courier_hidden"));
                                    // $(".courier_hidden input").prop("checked", true);
                                    $(".delivery-variants li").on('click', function () {
                                        $('.balloon-alert2').remove();
                                        $(".delivery-variants li").removeClass('checked');
                                        $(this).addClass("checked");
                                        $(".delivery-variants select").remove();
                                        $(this).find('input').prop('checked', true);
                                        let thisEl = $(this);
                                        switch($(this).attr('id')) {
                                            case "li_12":
                                                $("#li_12").parent().after($(".location-address"));
                                                $(".location-address").show();
                                                $(".delivery-list-wrap ul").remove();
                                                deliveryDisable();
                                                $(".total-costt").show();
                                                $("#ORDER_PROP_4 option").eq(1).show();
                                                let cachPay = document.querySelector('#ORDER_PROP_4 option[value="NAL_NAL"]');
                                                if (!cachPay)
                                                    $("#ORDER_PROP_4").append("<option value='NAL_NAL'>Оплата наличными</option>")
                                                ORDER_CONFIRM_BUTTON.style.display = 'none';
                                                $("#ORDER_PROP_14, #ORDER_PROP_15, #ORDER_PROP_16, #ORDER_PROP_17, #ORDER_PROP_18, #ORDER_PROP_19, #ORDER_PROP_20").val("");
                                                $("#ORDER_PROP_15").val($(this).text());
                                                thisEl.parent().find('ul').remove();
                                                $(".location-row.clearfix").slideDown('fast');
                                                openPharmChangeList();

                                                break;

                                            case "li_17":
                                                deliveryDisable();
                                                $(".total-costt").show();
                                                $("#ORDER_PROP_4 option").eq(0).prop('selected', true);
                                                $("#ORDER_PROP_4 option").eq(1).remove();
                                                ORDER_CONFIRM_BUTTON.style.display = 'none';
                                                $("#ORDER_PROP_14, #ORDER_PROP_15, #ORDER_PROP_16, #ORDER_PROP_17, #ORDER_PROP_18, #ORDER_PROP_19, #ORDER_PROP_20").val("");
                                                $("#ORDER_PROP_15").val($(this).text());
                                                thisEl.parent().find('ul').remove();
                                                $(".location-row.clearfix").slideUp('fast');
                                                if (!deliveryDisableGlobal) {
                                                    thisEl.append('<div style="position: absolute; margin-top: -7px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                        '<div></div><div><div></div></div></div></div>')
                                                }
                                                $.ajax({
                                                    type: "POST",
                                                    url: url,
                                                    data: {
                                                        action: "getAreaNP"
                                                    },
                                                    success: function (resp) {
                                                        if (!deliveryDisableGlobal) {
                                                            $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                            thisEl.after("<ul></ul>");
                                                            thisEl.next().append("<li><select id='areas-sel'>" + resp + "</select></li>");
                                                            $("#areas-sel").on('change', function () {
                                                                $("#ORDER_PROP_16").val("");
                                                                $("#ORDER_PROP_14").val($("#areas-sel option:selected").text());
                                                                $(this).parent().next().remove();
                                                                $(this).parent().next().remove();
                                                                $(this).after('<div style="position: absolute; margin-top: -6px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                                    '<div></div><div><div></div></div></div></div>')
                                                                $.ajax({
                                                                    type: "POST",
                                                                    url: url,
                                                                    data: {
                                                                        action: "getCityNP",
                                                                        area: $("#areas-sel option:selected").val()
                                                                    },
                                                                    success: function (resp) {
                                                                        deliveryDisable();
                                                                        $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                                        thisEl.next().append("<li><select id='cities-sel'>" + resp + "</select></li>");
                                                                        $("#cities-sel").on('change', function () {
                                                                            $("#ORDER_PROP_16").val($("#cities-sel option:selected").text());
                                                                            $(this).parent().next().remove();
                                                                            $(this).after('<div style="position: absolute; margin-top: -6px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                                                '<div></div><div><div></div></div></div></div>')
                                                                            $.ajax({
                                                                                type: "POST",
                                                                                url: url,
                                                                                data: {
                                                                                    action: "getStreetNP",
                                                                                    city: $("#cities-sel option:selected").val()
                                                                                },
                                                                                success: function (resp) {
                                                                                    deliveryDisable();
                                                                                    $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                                                    let obj = JSON.parse(resp)
                                                                                    let arr = [];
                                                                                    for (let item = 0; item < obj.length; item++) {
                                                                                        arr.push([
                                                                                            obj[item][0],
                                                                                            obj[item][1]
                                                                                        ]);
                                                                                    }

                                                                                    thisEl.next().append("<div class='np_street_wrap'><input placeholder='Вулиця' type='text' name='np_street' onkeyup='notLatin($(this), \"Разрешена только кириллица\")' /><input placeholder='Будинок' type='text' name='np_house' onkeyup='notLatin($(this), \"Разрешена только кириллица\")'/> <input placeholder='Квартира' type='text' name='np_flat' onkeyup='notLatin($(this), \"Разрешена только кириллица\")'/></div>");
                                                                                    $("input[name=np_street]").on('keyup', function () {
                                                                                        $(".np_street_wrap + ul").remove();
                                                                                        if (arr.length > 0)
                                                                                            $(".np_street_wrap").after("<ul></ul>");
                                                                                        if ($(this).val() == "")
                                                                                            $(".np_street_wrap + ul").remove()
                                                                                        for (let item = 0; item < arr.length; item++) {
                                                                                            if (arr[item][0].toLowerCase().indexOf($(this).val().toLowerCase()) != 0) {
                                                                                                continue;
                                                                                            }

                                                                                            $(".np_street_wrap + ul").append("<li id='" + arr[item][1] + "'>" + arr[item][0] + "</li>")
                                                                                        }

                                                                                        $(".np_street_wrap + ul li").on('click', function () {
                                                                                            $("input[name=np_street]").val($(this).text());
                                                                                            $(".np_street_wrap + ul").remove();
                                                                                        })
                                                                                    })
                                                                                    $("input[name=np_street]").focusout(function () {
                                                                                        if ($(this).val().length > 0 && !deliveryDisableGlobal) {
                                                                                            ORDER_CONFIRM_BUTTON.style.display = 'block';
                                                                                        } else {
                                                                                            ORDER_CONFIRM_BUTTON.style.display = 'none';
                                                                                        }
                                                                                    })
                                                                                }
                                                                            });
                                                                        })
                                                                    }
                                                                });
                                                            })
                                                        }
                                                    }
                                                });
                                                break;

                                            case "li_18":
                                                deliveryDisable();
                                                $(".total-costt").show();
                                                $("#ORDER_PROP_4 option").eq(0).prop('selected', true);
                                                $("#ORDER_PROP_4 option").eq(1).remove();
                                                ORDER_CONFIRM_BUTTON.style.display = 'none';
                                                $(".location-row.clearfix").slideUp('fast');
                                                $("#ORDER_PROP_14, #ORDER_PROP_15, #ORDER_PROP_16, #ORDER_PROP_17, #ORDER_PROP_18, #ORDER_PROP_19, #ORDER_PROP_20").val("");
                                                $("#ORDER_PROP_15").val($(this).text());
                                                thisEl.parent().find('ul').remove();
                                                if (!deliveryDisableGlobal) {
                                                    thisEl.append('<div style="position: absolute; margin-top: -7px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                    '<div></div><div><div></div></div></div></div>')
                                                }

                                                $.ajax({
                                                    type: "POST",
                                                    url: url,
                                                    data: {
                                                        action: "getAreaNP"
                                                    },
                                                    success: function(resp) {
                                                        if (!deliveryDisableGlobal) {
                                                            $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                            thisEl.after("<ul></ul>");
                                                            thisEl.next().append("<li><select id='areas-sel'>" + resp + "</select></li>");
                                                            $("#areas-sel").on('change', function () {
                                                                $("#ORDER_PROP_16, #ORDER_PROP_20").val("");
                                                                $("#ORDER_PROP_14").val($("#areas-sel option:selected").text());
                                                                $(this).parent().next().remove();
                                                                $(this).parent().next().remove();
                                                                $(this).after('<div style="position: absolute; margin-top: -6px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                                    '<div></div><div><div></div></div></div></div>')
                                                                $.ajax({
                                                                    type: "POST",
                                                                    url: url,
                                                                    data: {
                                                                        action: "getCityNP",
                                                                        area: $("#areas-sel option:selected").val()
                                                                    },
                                                                    success: function(resp) {
                                                                        deliveryDisable();
                                                                        $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                                        thisEl.next().append("<li><select id='cities-sel'>" + resp + "</select></li>");
                                                                        $("#cities-sel").on('change', function () {
                                                                            $("#ORDER_PROP_20").val("");
                                                                            $("#ORDER_PROP_16").val($("#cities-sel option:selected").text());
                                                                            $(this).parent().next().remove();
                                                                            $(this).after('<div style="position: absolute; margin-top: -6px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                                                '<div></div><div><div></div></div></div></div>')
                                                                            $.ajax({
                                                                                type: "POST",
                                                                                url: url,
                                                                                data: {
                                                                                    action: "getWarehousesNP",
                                                                                    wareHouse: $("#cities-sel option:selected").val()
                                                                                },
                                                                                success: function(resp) {
                                                                                    deliveryDisable();
                                                                                    $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                                                    thisEl.next().append("<li><select id='warehouses-sel'>" + resp + "</select></li>");

                                                                                    $("#warehouses-sel").on('change', function () {
                                                                                        $("#ORDER_PROP_20").val("");
                                                                                        deliveryDisable();
                                                                                        if ($("#warehouses-sel option:selected").val() != 0 && !deliveryDisableGlobal) {
                                                                                            $("#ORDER_PROP_20").val($("#warehouses-sel option:selected").val());
                                                                                            ORDER_CONFIRM_BUTTON.style.display = 'block';
                                                                                        } else
                                                                                            ORDER_CONFIRM_BUTTON.style.display = 'none';
                                                                                    })
                                                                                }
                                                                            });
                                                                        })
                                                                    }
                                                                });
                                                            })
                                                        }
                                                    }
                                                });

                                                break;

                                            case "li_19":
                                                deliveryDisable();
                                                $(".total-costt").show();
                                                $("#ORDER_PROP_4 option").eq(0).prop('selected', true);
                                                $("#ORDER_PROP_4 option").eq(1).remove();
                                                ORDER_CONFIRM_BUTTON.style.display = 'none';
                                                $(".location-row.clearfix").slideUp('fast');
                                                $("#ORDER_PROP_14, #ORDER_PROP_15, #ORDER_PROP_16, #ORDER_PROP_17, #ORDER_PROP_18, #ORDER_PROP_19, #ORDER_PROP_20, ORDER_PROP_21, ORDER_PROP_22, ORDER_PROP_23").val("");
                                                $("#ORDER_PROP_15").val($(this).text());
                                                thisEl.parent().find('ul').remove();
                                                if (!deliveryDisableGlobal) {
                                                    thisEl.append('<div style="position: absolute; margin-top: -7px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                        '<div></div><div><div></div></div></div></div>')
                                                }

                                                $.ajax({
                                                    type: "POST",
                                                    url: url,
                                                    data: {
                                                        action: "getAreaUkr"
                                                    },
                                                    success: function (resp) {
                                                        if (!deliveryDisableGlobal) {
                                                            $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                            thisEl.after("<ul></ul>");
                                                            thisEl.next().append("<li><select id='ukr-areas-sel'>" + resp + "</select></li>");
                                                            $("#ukr-areas-sel").on('change', function () {
                                                                $("#ORDER_PROP_22, #ORDER_PROP_23").val("");
                                                                $("#ORDER_PROP_21").val($("#ukr-areas-sel option:selected").text());
                                                                $("#ORDER_PROP_24").val($("#ukr-areas-sel option:selected").val());
                                                                $(this).parent().next().remove();
                                                                $(this).parent().next().remove();
                                                                $(this).after('<div style="position: absolute; margin-top: -6px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                                    '<div></div><div><div></div></div></div></div>');
                                                                $.ajax({
                                                                    type: "POST",
                                                                    url: url,
                                                                    data: {
                                                                        action: "getCityUkr",
                                                                        area: $("#ukr-areas-sel option:selected").val()
                                                                    },
                                                                    success: function (resp) {
                                                                        deliveryDisable();
                                                                        $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                                        thisEl.next().append("<li><select id='ukr-cities-sel'>" + resp + "</select></li>");
                                                                        $("#ukr-cities-sel").on('change', function () {
                                                                            $("#ORDER_PROP_23").val("");
                                                                            $("#ORDER_PROP_22").val($("#ukr-cities-sel option:selected").text());
                                                                            $("#ORDER_PROP_27").val($("#ukr-cities-sel option:selected").val());
                                                                            $("#ORDER_PROP_25").val($("#ukr-cities-sel option:selected").data('region-id'));
                                                                            $("#ORDER_PROP_26").val($("#ukr-cities-sel option:selected").data('region-name'));
                                                                            $(this).parent().next().remove();
                                                                            $(this).after('<div style="position: absolute; margin-top: -6px;" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                                                                                '<div></div><div><div></div></div></div></div>')
                                                                            $.ajax({
                                                                                type: "POST",
                                                                                url: url,
                                                                                data: {
                                                                                    action: "getWarehousesUkr",
                                                                                    wareHouse: $("#ukr-cities-sel option:selected").val()
                                                                                },
                                                                                success: function(resp) {
                                                                                    deliveryDisable();
                                                                                    $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide();
                                                                                    thisEl.next().append("<li><select id='ukr-warehouses-sel'>" + resp + "</select></li>");
                                                                                    $("#ukr-warehouses-sel").on('change', function () {
                                                                                        $("#ORDER_PROP_23").val("");
                                                                                        deliveryDisable();
                                                                                        if ($("#ukr-warehouses-sel option:selected").val() != 0 && !deliveryDisableGlobal) {
                                                                                            $("#ORDER_PROP_23").val($("#ukr-warehouses-sel option:selected").val());
                                                                                            $("#ORDER_PROP_28").val($("#ukr-warehouses-sel option:selected").data('street-id'));
                                                                                            $("#ORDER_PROP_29").val($("#ukr-warehouses-sel option:selected").data('street-name'));
                                                                                            $("#ORDER_PROP_30").val($("#ukr-warehouses-sel option:selected").data('house-number'));
                                                                                            $("#ORDER_PROP_31").val($("#ukr-warehouses-sel option:selected").data('postindex'));
                                                                                            $("#ORDER_PROP_32").val($("#ukr-warehouses-sel option:selected").data('street-type'));
                                                                                            ORDER_CONFIRM_BUTTON.style.display = 'block';
                                                                                        } else
                                                                                            ORDER_CONFIRM_BUTTON.style.display = 'none';
                                                                                    })
                                                                                }
                                                                            });
                                                                        })
                                                                    }
                                                                });
                                                            });
                                                        }
                                                    }
                                                });

                                                break;

                                            case "li_20":

                                                $(".delivery-list-wrap ul").remove();
                                                $(".location-row.clearfix").slideDown('fast');
                                                $("#ORDER_PROP_4 option").eq(0).prop('selected', true);
                                                $("#ORDER_PROP_4 option").eq(1).remove();
                                                $("#ORDER_PROP_4").append("<option value='NAL_COURIER'>Оплата наличными курьеру</option>");
                                                // $("#ORDER_PROP_4").append("<option value='CARD_COURIER'>Оплата картой курьеру</option>");

                                                $("#ORDER_PROP_14, #ORDER_PROP_15, #ORDER_PROP_16, #ORDER_PROP_17, #ORDER_PROP_18, #ORDER_PROP_19, #ORDER_PROP_20, ORDER_PROP_21, ORDER_PROP_22, ORDER_PROP_23").val("");
                                                $("#ORDER_PROP_15").val($(this).text());

                                                $("#li_20").parent().after("" +
                                                    "<div style='display:none' class='delivery-courier'>" +
                                                    "<p class='delivery-courier-field-title'>Заполните обязательные поля:</p>" +
                                                    "<input class='delivery-courier-field' type='text' name='courier-fio' placeholder='Ф.И.О. получателя*' id='courier-delivery-fio'>" +
                                                    "<input class='delivery-courier-field' type='tel' name='courier-phone' placeholder='Телефон получателя*' id='courier-delivery-phone' value='" + $("#ORDER_PROP_3").val() + "'>" +
                                                    "<p class='delivery-courier-address-title'>Адрес:*</p>" +
                                                    "<input type='text' id='delivery-courier-address' disabled=disabled style='border:none;color:#666;font-style:italic'>" +
                                                    "<input type='hidden' id='delivery-courier-lat'>" +
                                                    "<input type='hidden' id='delivery-courier-lng'>" +
                                                    "<div id='map'><div id='map_logo'></div></div>" +
                                                    "<p class='delivery-courier-field-required'>* поля, обязательные для заполнения</p>" +
                                                    "</div>");
                                                setTimeout(() => {
                                                    $('.delivery-courier').slideDown('fast');
                                                    userFIO();

                                                    let map = L.map('map').setView([48.7, 30], 4);

                                                    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                                                        attribution: '&copy; <a href="https://osm.org/copyright">OpenStreetMap</a> contributors'
                                                    }).addTo(map);

                                                    let searchControl = L.esri.Geocoding.geosearch({
                                                        expanded: true,
                                                        collapseAfterResult: false,
                                                        placeholder: 'Введите адрес доставки...',
                                                        title: 'Введите адрес доставки...'
                                                    }).addTo(map);

                                                    let addressInput = document.querySelector('.geocoder-control-input.leaflet-bar');
                                                    let courierCity = document.querySelector('#ord_oblast');
                                                    addressInput.value = courierCity.value + ', ';

                                                    let results = L.layerGroup().addTo(map);

                                                    searchControl.on('results', function (data) {
                                                        results.clearLayers();
                                                        for (let i = data.results.length - 1; i >= 0; i--) {
                                                            results.addLayer(L.marker(data.results[i].latlng));
                                                            $("#delivery-courier-address").val(data.results[i].properties.City + ", " + data.results[i].properties.ShortLabel);
                                                            $("#delivery-courier-lat").val(data.results[i].latlng.lat);
                                                            $("#delivery-courier-lng").val(data.results[i].latlng.lng);
                                                        }
                                                    });
                                                }, 100);
                                                $("#courier-delivery-phone").mask("+38 (999) 999-99-99");
                                                $(".location-address").hide();
                                                $.ajax({
                                                    type: "POST",
                                                    url: url,
                                                    data: {
                                                        action: "getCourierPrices",
                                                        deliveryId: 20,
                                                        totalSum: $("#totalOrder").text()
                                                    },
                                                    success: function(resp) {

                                                        $(".total-costt").hide();
                                                        $(".bx_ordercart_order_sum").prepend(resp);
                                                        $("#ORDER_PROP_33").val($("#delivery_cost").text());
                                                        ORDER_CONFIRM_BUTTON.style.display = 'block';
                                                        /*$("ul.delivery-list .delivery-list-wrap:last-child, .delivery-courier").wrapAll("<div class='courier-data-wrap'></div>");*/
                                                    }
                                                });
                                                break;

                                            default:
                                                $(".location-row.clearfix").slideDown('fast');
                                                break
                                        }
                                    })
                                }
                            }
                        });
                    }

                    deliveryVariants();

                    // Условия выбора списка городов
                    function enterData(value) {
                        if(!value) return;
                        ord_oblast_name.parentNode.style.display = 'block';
                        ord_oblast_name.style.display = 'block';
                        ord_oblast_name_list.style.display ='block';
                        ord_oblast_name_list.dataset.vis = 'block';
                        let doubleTown = new Array();
                        for(el in ord_oblast_name.children){
                            //ord_oblast_name.children[el].style.display='none';
                            if(!ord_oblast_name.children.hasOwnProperty(el)) continue;
                            let stringName = ord_oblast_name.children[el].innerHTML.toLowerCase();
                            let re = new RegExp('^' + value.toLowerCase(), 'ig');
                            if(stringName.match(re)){
                                // $("#ord_city").text("Выбрать город...")
                                if (doubleTown.indexOf(stringName) !== -1){
                                    continue
                                }else{
                                    doubleTown.push(stringName)
                                    ord_oblast_name.children[el].style.display='';}
                            } else {
                                ord_oblast_name.children[el].style.display='none';
                            }
                        }
                    }

                    ord_oblast.onkeyup = function(event) {
                        $(".location-address").hide()
                        event = event || window.event;
                        let target = event.target || event.srcElement;
                        let erase = event.keyCode;
                        question.style.display = 'none';
                        //ord_city.innerHTML = 'Выбрать адрес аптеки...';
                        ord_oblast_apt.innerHTML = '';
                        ord_oblast_apt.style.display = 'none';
                        if (erase == 8) {
                            oblApt.style.display = 'none';
                            oblApt.innerHTML = '';
                            // ord_city.innerHTML = '';
                            $("#ord_city input").val('')
                            question.style.display = 'inline-block';
                            //order.classList.add('order-empty-error');
                            ord_oblast.placeholder = 'Выбрать город...';
                            // ord_city.innerHTML = 'Выбрать адрес аптеки...';
                            if (ord_oblast.value == '') {
                                ORDER_CONFIRM_BUTTON.style.display = 'none';
                            }
                            ord_oblast_name.style.display = 'none';
                        }
                        //console.log(target.value);
                        let re = /[а-я\d\,\ ]+/ig;
                        let con = re.test(target.value);
                        //console.log(con);
                        if(con == true){
                            target.style.color='';
                            order.classList.remove('order-empty-error');
                            if(target.value.length > 0){
                                enterData(target.value);
                            }
                        } else {
                           target.style.color='red';
                           ord_oblast_name.style.display = 'none';
                        }
                    }

                    ord_city.onclick = function(event) {
                        return false
                        if (ord_oblast.value != '') {
                            ord_city.nextSibling.style.display = 'block';
                        }

                    }

                    // Конечное формирование заказа в скрытых полях
                    let cityAllRez = document.getElementById('ord_oblast_apt');
                    cityAllRez.onclick = function(event) {
                        event = event || window.event;
                        let targetItog = event.target || event.srcElement;
                        let aptIn = targetItog.innerHTML;
                        // ord_city.innerHTML = aptIn;
                        oblApt.style.display = 'none';
                        $("div.location-address input[type=search]").val(aptIn)
                        // console.log(aptIn)
                        ORDER_CONFIRM_BUTTON.style.display = 'block';
                        //console.log(aptIn);
                        id = targetItog.id;
                        inp_loc.value = id;
                        inp_loc.innerHTML = id;
                        // inp_loc_adr.value = itogCity + ', ' + ord_city.innerHTML;
                        inp_loc_adr.value = itogCity + ', ' + $("#ord_city input").val();
                        // inp_loc_adr.innerHTML = itogCity + ', ' + ord_city.innerHTML;
                        inp_loc_adr.innerHTML = itogCity + ', ' + $("#ord_city input").val();
                    }

                    // ORDER_CONFIRM_BUTTON.style.display = 'block';

                    $("#ORDER_PROP_2").focusout(function () {
                        let thisEl = $(this)
                        thisEl.after('<div style="position: absolute" class="loadingio-spinner-dual-ring-qmu8mqsk81"><div class="ldio-oojr64tg0sa">\n' +
                            '<div></div><div><div></div></div>\n' +
                            '</div></div>')
                        $.ajax({
                            type: "POST",
                            url: "/bitrix/templates/eshop_adapt_MC/components/medservice/MCsale.order.ajax/orderMC/check_email.php",
                            data: {
                                action: "checkEmail",
                                email: $(this).val(),
                            },
                            success: function(resp) {
                                $(".loadingio-spinner-dual-ring-qmu8mqsk81").hide()
                                if (resp) {
                                    thisEl.css({
                                        border: '1px solid red'
                                    })
                                    if(!$('*').is('.email-is-busy'))
                                        thisEl.after("<div class='email-is-busy alert alert-info'>Такой e-mail занят. Если это Ваш, то, пожалуйста, авторизуйтесь, нажав на кнопку «Я постоянный клиент»</div>")
                                } else {
                                    $(".email-is-busy").remove()
                                    thisEl.css({
                                        border: '1px solid #d5dadc'
                                    })
                                }
                            }
                        });
                    })
                </script>
                <?
                if($arParams["DELIVERY_NO_AJAX"] == "N") {
                    ?>
                    <div style="display:none;"><?$APPLICATION->IncludeComponent("bitrix:sale.ajax.delivery.calculator", "", array(), null, array('HIDE_ICONS' => 'Y')); ?></div>
                    <?
                }
            }
            else
            {
                ?>
                <script type="text/javascript">
                    top.BX('confirmorder').value = 'Y';
                    top.BX('profile_change').value = 'N';
                </script>
                <?
                die();
            }
        }
    }
    ?>
    </div>
    <?php if (!$USER->IsAuthorized()){?>
</div>
<?php }?>


<?php if (CSaleLocation::isLocationProEnabled()) {?>

    <div style="display: none">
        <?// we need to have all styles for sale.location.selector.steps,
    //but RestartBuffer() cuts off document head with styles in it?>
        <?$APPLICATION->IncludeComponent(
            "bitrix:sale.location.selector.steps",
            "MC",
            array(
            ),
            false
        );?>
        <?$APPLICATION->IncludeComponent(
            "bitrix:sale.location.selector.search",
            ".default",
            array(
            ),
            false
        );?>
    </div>

<?php }?>

